# Air configuration file
# For more details, visit: https://github.com/air-verse/air/blob/master/air_example.toml

# Project root directory
root = "."
tmp_dir = "tmp"

# Delay in milliseconds to prevent frequent builds
delay = 1000 # ms

# Build command
[build]
cmd = "go build -o ./tmp/main ./cmd/api"
