name: useGrant_backend

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - usegrant_backend-pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}

  backend:
    depends_on:
      - postgres
    build:
      context: .
      target: development
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    restart: always

volumes:
  usegrant_backend-pgdata:
