urls:
  self:
    issuer: http://hydra:4444

oauth2:
  token_hook: http://backend:3000/api/v1/ory-token-hook
  allowed_top_level_claims:
    - custom
    - iss
  mirror_top_level_claims: false

webfinger:
  oidc_discovery:
    supported_scope:
      - openid

secrets:
  system:
    # https://www.ory.sh/docs/hydra/self-hosted/secrets-key-rotation#rotation-of-hmac-token-signing-and-database-and-cookie-encryption-keys
    # keep old encryption key and add new one if required
    # - new key here
    - eb0f6de2-6ced-4217-ba5a-45fd63d79205

oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise
    pairwise:
      salt: "1234567890"
  dynamic_client_registration:
    enabled: false
    default_scope:
      - openid

strategies:
  scope: exact
  access_token: jwt
  jwt:
    scope_claim: list

log:
  level: debug
