// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/usegranthq/backend/ent/oidcclient"
	"github.com/usegranthq/backend/ent/project"
)

// OidcClientCreate is the builder for creating a OidcClient entity.
type OidcClientCreate struct {
	config
	mutation *OidcClientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (occ *OidcClientCreate) SetName(s string) *OidcClientCreate {
	occ.mutation.SetName(s)
	return occ
}

// SetAudience sets the "audience" field.
func (occ *OidcClientCreate) SetAudience(s string) *OidcClientCreate {
	occ.mutation.SetAudience(s)
	return occ
}

// SetClientRefID sets the "client_ref_id" field.
func (occ *OidcClientCreate) SetClientRefID(s string) *OidcClientCreate {
	occ.mutation.SetClientRefID(s)
	return occ
}

// SetClientID sets the "client_id" field.
func (occ *OidcClientCreate) SetClientID(s string) *OidcClientCreate {
	occ.mutation.SetClientID(s)
	return occ
}

// SetCreatedAt sets the "created_at" field.
func (occ *OidcClientCreate) SetCreatedAt(t time.Time) *OidcClientCreate {
	occ.mutation.SetCreatedAt(t)
	return occ
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (occ *OidcClientCreate) SetNillableCreatedAt(t *time.Time) *OidcClientCreate {
	if t != nil {
		occ.SetCreatedAt(*t)
	}
	return occ
}

// SetUpdatedAt sets the "updated_at" field.
func (occ *OidcClientCreate) SetUpdatedAt(t time.Time) *OidcClientCreate {
	occ.mutation.SetUpdatedAt(t)
	return occ
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (occ *OidcClientCreate) SetNillableUpdatedAt(t *time.Time) *OidcClientCreate {
	if t != nil {
		occ.SetUpdatedAt(*t)
	}
	return occ
}

// SetID sets the "id" field.
func (occ *OidcClientCreate) SetID(u uuid.UUID) *OidcClientCreate {
	occ.mutation.SetID(u)
	return occ
}

// SetNillableID sets the "id" field if the given value is not nil.
func (occ *OidcClientCreate) SetNillableID(u *uuid.UUID) *OidcClientCreate {
	if u != nil {
		occ.SetID(*u)
	}
	return occ
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (occ *OidcClientCreate) SetProjectID(id uuid.UUID) *OidcClientCreate {
	occ.mutation.SetProjectID(id)
	return occ
}

// SetProject sets the "project" edge to the Project entity.
func (occ *OidcClientCreate) SetProject(p *Project) *OidcClientCreate {
	return occ.SetProjectID(p.ID)
}

// Mutation returns the OidcClientMutation object of the builder.
func (occ *OidcClientCreate) Mutation() *OidcClientMutation {
	return occ.mutation
}

// Save creates the OidcClient in the database.
func (occ *OidcClientCreate) Save(ctx context.Context) (*OidcClient, error) {
	occ.defaults()
	return withHooks(ctx, occ.sqlSave, occ.mutation, occ.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (occ *OidcClientCreate) SaveX(ctx context.Context) *OidcClient {
	v, err := occ.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (occ *OidcClientCreate) Exec(ctx context.Context) error {
	_, err := occ.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (occ *OidcClientCreate) ExecX(ctx context.Context) {
	if err := occ.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (occ *OidcClientCreate) defaults() {
	if _, ok := occ.mutation.CreatedAt(); !ok {
		v := oidcclient.DefaultCreatedAt()
		occ.mutation.SetCreatedAt(v)
	}
	if _, ok := occ.mutation.UpdatedAt(); !ok {
		v := oidcclient.DefaultUpdatedAt()
		occ.mutation.SetUpdatedAt(v)
	}
	if _, ok := occ.mutation.ID(); !ok {
		v := oidcclient.DefaultID()
		occ.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (occ *OidcClientCreate) check() error {
	if _, ok := occ.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OidcClient.name"`)}
	}
	if v, ok := occ.mutation.Name(); ok {
		if err := oidcclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OidcClient.name": %w`, err)}
		}
	}
	if _, ok := occ.mutation.Audience(); !ok {
		return &ValidationError{Name: "audience", err: errors.New(`ent: missing required field "OidcClient.audience"`)}
	}
	if v, ok := occ.mutation.Audience(); ok {
		if err := oidcclient.AudienceValidator(v); err != nil {
			return &ValidationError{Name: "audience", err: fmt.Errorf(`ent: validator failed for field "OidcClient.audience": %w`, err)}
		}
	}
	if _, ok := occ.mutation.ClientRefID(); !ok {
		return &ValidationError{Name: "client_ref_id", err: errors.New(`ent: missing required field "OidcClient.client_ref_id"`)}
	}
	if v, ok := occ.mutation.ClientRefID(); ok {
		if err := oidcclient.ClientRefIDValidator(v); err != nil {
			return &ValidationError{Name: "client_ref_id", err: fmt.Errorf(`ent: validator failed for field "OidcClient.client_ref_id": %w`, err)}
		}
	}
	if _, ok := occ.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OidcClient.client_id"`)}
	}
	if v, ok := occ.mutation.ClientID(); ok {
		if err := oidcclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OidcClient.client_id": %w`, err)}
		}
	}
	if _, ok := occ.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OidcClient.created_at"`)}
	}
	if _, ok := occ.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OidcClient.updated_at"`)}
	}
	if len(occ.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "OidcClient.project"`)}
	}
	return nil
}

func (occ *OidcClientCreate) sqlSave(ctx context.Context) (*OidcClient, error) {
	if err := occ.check(); err != nil {
		return nil, err
	}
	_node, _spec := occ.createSpec()
	if err := sqlgraph.CreateNode(ctx, occ.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	occ.mutation.id = &_node.ID
	occ.mutation.done = true
	return _node, nil
}

func (occ *OidcClientCreate) createSpec() (*OidcClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OidcClient{config: occ.config}
		_spec = sqlgraph.NewCreateSpec(oidcclient.Table, sqlgraph.NewFieldSpec(oidcclient.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = occ.conflict
	if id, ok := occ.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := occ.mutation.Name(); ok {
		_spec.SetField(oidcclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := occ.mutation.Audience(); ok {
		_spec.SetField(oidcclient.FieldAudience, field.TypeString, value)
		_node.Audience = value
	}
	if value, ok := occ.mutation.ClientRefID(); ok {
		_spec.SetField(oidcclient.FieldClientRefID, field.TypeString, value)
		_node.ClientRefID = value
	}
	if value, ok := occ.mutation.ClientID(); ok {
		_spec.SetField(oidcclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := occ.mutation.CreatedAt(); ok {
		_spec.SetField(oidcclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := occ.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := occ.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oidcclient.ProjectTable,
			Columns: []string{oidcclient.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_oidc_clients = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OidcClient.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OidcClientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (occ *OidcClientCreate) OnConflict(opts ...sql.ConflictOption) *OidcClientUpsertOne {
	occ.conflict = opts
	return &OidcClientUpsertOne{
		create: occ,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (occ *OidcClientCreate) OnConflictColumns(columns ...string) *OidcClientUpsertOne {
	occ.conflict = append(occ.conflict, sql.ConflictColumns(columns...))
	return &OidcClientUpsertOne{
		create: occ,
	}
}

type (
	// OidcClientUpsertOne is the builder for "upsert"-ing
	//  one OidcClient node.
	OidcClientUpsertOne struct {
		create *OidcClientCreate
	}

	// OidcClientUpsert is the "OnConflict" setter.
	OidcClientUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *OidcClientUpsert) SetName(v string) *OidcClientUpsert {
	u.Set(oidcclient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OidcClientUpsert) UpdateName() *OidcClientUpsert {
	u.SetExcluded(oidcclient.FieldName)
	return u
}

// SetAudience sets the "audience" field.
func (u *OidcClientUpsert) SetAudience(v string) *OidcClientUpsert {
	u.Set(oidcclient.FieldAudience, v)
	return u
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *OidcClientUpsert) UpdateAudience() *OidcClientUpsert {
	u.SetExcluded(oidcclient.FieldAudience)
	return u
}

// SetClientRefID sets the "client_ref_id" field.
func (u *OidcClientUpsert) SetClientRefID(v string) *OidcClientUpsert {
	u.Set(oidcclient.FieldClientRefID, v)
	return u
}

// UpdateClientRefID sets the "client_ref_id" field to the value that was provided on create.
func (u *OidcClientUpsert) UpdateClientRefID() *OidcClientUpsert {
	u.SetExcluded(oidcclient.FieldClientRefID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OidcClientUpsert) SetClientID(v string) *OidcClientUpsert {
	u.Set(oidcclient.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OidcClientUpsert) UpdateClientID() *OidcClientUpsert {
	u.SetExcluded(oidcclient.FieldClientID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OidcClientUpsert) SetUpdatedAt(v time.Time) *OidcClientUpsert {
	u.Set(oidcclient.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OidcClientUpsert) UpdateUpdatedAt() *OidcClientUpsert {
	u.SetExcluded(oidcclient.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oidcclient.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OidcClientUpsertOne) UpdateNewValues() *OidcClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oidcclient.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oidcclient.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OidcClientUpsertOne) Ignore() *OidcClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OidcClientUpsertOne) DoNothing() *OidcClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OidcClientCreate.OnConflict
// documentation for more info.
func (u *OidcClientUpsertOne) Update(set func(*OidcClientUpsert)) *OidcClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OidcClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OidcClientUpsertOne) SetName(v string) *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OidcClientUpsertOne) UpdateName() *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateName()
	})
}

// SetAudience sets the "audience" field.
func (u *OidcClientUpsertOne) SetAudience(v string) *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *OidcClientUpsertOne) UpdateAudience() *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateAudience()
	})
}

// SetClientRefID sets the "client_ref_id" field.
func (u *OidcClientUpsertOne) SetClientRefID(v string) *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetClientRefID(v)
	})
}

// UpdateClientRefID sets the "client_ref_id" field to the value that was provided on create.
func (u *OidcClientUpsertOne) UpdateClientRefID() *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateClientRefID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OidcClientUpsertOne) SetClientID(v string) *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OidcClientUpsertOne) UpdateClientID() *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateClientID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OidcClientUpsertOne) SetUpdatedAt(v time.Time) *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OidcClientUpsertOne) UpdateUpdatedAt() *OidcClientUpsertOne {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OidcClientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OidcClientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OidcClientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OidcClientUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OidcClientUpsertOne.ID is not supported by MySQL driver. Use OidcClientUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OidcClientUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OidcClientCreateBulk is the builder for creating many OidcClient entities in bulk.
type OidcClientCreateBulk struct {
	config
	err      error
	builders []*OidcClientCreate
	conflict []sql.ConflictOption
}

// Save creates the OidcClient entities in the database.
func (occb *OidcClientCreateBulk) Save(ctx context.Context) ([]*OidcClient, error) {
	if occb.err != nil {
		return nil, occb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(occb.builders))
	nodes := make([]*OidcClient, len(occb.builders))
	mutators := make([]Mutator, len(occb.builders))
	for i := range occb.builders {
		func(i int, root context.Context) {
			builder := occb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OidcClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, occb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = occb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, occb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, occb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (occb *OidcClientCreateBulk) SaveX(ctx context.Context) []*OidcClient {
	v, err := occb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (occb *OidcClientCreateBulk) Exec(ctx context.Context) error {
	_, err := occb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (occb *OidcClientCreateBulk) ExecX(ctx context.Context) {
	if err := occb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OidcClient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OidcClientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (occb *OidcClientCreateBulk) OnConflict(opts ...sql.ConflictOption) *OidcClientUpsertBulk {
	occb.conflict = opts
	return &OidcClientUpsertBulk{
		create: occb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (occb *OidcClientCreateBulk) OnConflictColumns(columns ...string) *OidcClientUpsertBulk {
	occb.conflict = append(occb.conflict, sql.ConflictColumns(columns...))
	return &OidcClientUpsertBulk{
		create: occb,
	}
}

// OidcClientUpsertBulk is the builder for "upsert"-ing
// a bulk of OidcClient nodes.
type OidcClientUpsertBulk struct {
	create *OidcClientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oidcclient.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OidcClientUpsertBulk) UpdateNewValues() *OidcClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oidcclient.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oidcclient.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OidcClient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OidcClientUpsertBulk) Ignore() *OidcClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OidcClientUpsertBulk) DoNothing() *OidcClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OidcClientCreateBulk.OnConflict
// documentation for more info.
func (u *OidcClientUpsertBulk) Update(set func(*OidcClientUpsert)) *OidcClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OidcClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OidcClientUpsertBulk) SetName(v string) *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OidcClientUpsertBulk) UpdateName() *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateName()
	})
}

// SetAudience sets the "audience" field.
func (u *OidcClientUpsertBulk) SetAudience(v string) *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *OidcClientUpsertBulk) UpdateAudience() *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateAudience()
	})
}

// SetClientRefID sets the "client_ref_id" field.
func (u *OidcClientUpsertBulk) SetClientRefID(v string) *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetClientRefID(v)
	})
}

// UpdateClientRefID sets the "client_ref_id" field to the value that was provided on create.
func (u *OidcClientUpsertBulk) UpdateClientRefID() *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateClientRefID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OidcClientUpsertBulk) SetClientID(v string) *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OidcClientUpsertBulk) UpdateClientID() *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateClientID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OidcClientUpsertBulk) SetUpdatedAt(v time.Time) *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OidcClientUpsertBulk) UpdateUpdatedAt() *OidcClientUpsertBulk {
	return u.Update(func(s *OidcClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OidcClientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OidcClientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OidcClientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OidcClientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
