// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/usegranthq/backend/ent/oidcclient"
	"github.com/usegranthq/backend/ent/project"
	"github.com/usegranthq/backend/ent/schema"
	"github.com/usegranthq/backend/ent/user"
	"github.com/usegranthq/backend/ent/usersession"
	"github.com/usegranthq/backend/ent/userverification"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oidcclientFields := schema.OidcClient{}.Fields()
	_ = oidcclientFields
	// oidcclientDescName is the schema descriptor for name field.
	oidcclientDescName := oidcclientFields[1].Descriptor()
	// oidcclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oidcclient.NameValidator = oidcclientDescName.Validators[0].(func(string) error)
	// oidcclientDescClientID is the schema descriptor for client_id field.
	oidcclientDescClientID := oidcclientFields[2].Descriptor()
	// oidcclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oidcclient.ClientIDValidator = oidcclientDescClientID.Validators[0].(func(string) error)
	// oidcclientDescClientSecret is the schema descriptor for client_secret field.
	oidcclientDescClientSecret := oidcclientFields[3].Descriptor()
	// oidcclient.ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	oidcclient.ClientSecretValidator = oidcclientDescClientSecret.Validators[0].(func(string) error)
	// oidcclientDescCreatedAt is the schema descriptor for created_at field.
	oidcclientDescCreatedAt := oidcclientFields[4].Descriptor()
	// oidcclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oidcclient.DefaultCreatedAt = oidcclientDescCreatedAt.Default.(func() time.Time)
	// oidcclientDescUpdatedAt is the schema descriptor for updated_at field.
	oidcclientDescUpdatedAt := oidcclientFields[5].Descriptor()
	// oidcclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oidcclient.DefaultUpdatedAt = oidcclientDescUpdatedAt.Default.(func() time.Time)
	// oidcclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oidcclient.UpdateDefaultUpdatedAt = oidcclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oidcclientDescID is the schema descriptor for id field.
	oidcclientDescID := oidcclientFields[0].Descriptor()
	// oidcclient.DefaultID holds the default value on creation for the id field.
	oidcclient.DefaultID = oidcclientDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[4].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescToken is the schema descriptor for token field.
	usersessionDescToken := usersessionFields[1].Descriptor()
	// usersession.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	usersession.TokenValidator = usersessionDescToken.Validators[0].(func(string) error)
	// usersessionDescCreatedAt is the schema descriptor for created_at field.
	usersessionDescCreatedAt := usersessionFields[3].Descriptor()
	// usersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersession.DefaultCreatedAt = usersessionDescCreatedAt.Default.(func() time.Time)
	// usersessionDescUpdatedAt is the schema descriptor for updated_at field.
	usersessionDescUpdatedAt := usersessionFields[4].Descriptor()
	// usersession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersession.DefaultUpdatedAt = usersessionDescUpdatedAt.Default.(func() time.Time)
	// usersession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersession.UpdateDefaultUpdatedAt = usersessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usersessionDescID is the schema descriptor for id field.
	usersessionDescID := usersessionFields[0].Descriptor()
	// usersession.DefaultID holds the default value on creation for the id field.
	usersession.DefaultID = usersessionDescID.Default.(func() uuid.UUID)
	userverificationFields := schema.UserVerification{}.Fields()
	_ = userverificationFields
	// userverificationDescAttemptID is the schema descriptor for attempt_id field.
	userverificationDescAttemptID := userverificationFields[1].Descriptor()
	// userverification.DefaultAttemptID holds the default value on creation for the attempt_id field.
	userverification.DefaultAttemptID = userverificationDescAttemptID.Default.(func() uuid.UUID)
	// userverificationDescCode is the schema descriptor for code field.
	userverificationDescCode := userverificationFields[2].Descriptor()
	// userverification.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	userverification.CodeValidator = userverificationDescCode.Validators[0].(func(string) error)
	// userverificationDescAttempts is the schema descriptor for attempts field.
	userverificationDescAttempts := userverificationFields[3].Descriptor()
	// userverification.DefaultAttempts holds the default value on creation for the attempts field.
	userverification.DefaultAttempts = userverificationDescAttempts.Default.(int)
	// userverificationDescCreatedAt is the schema descriptor for created_at field.
	userverificationDescCreatedAt := userverificationFields[5].Descriptor()
	// userverification.DefaultCreatedAt holds the default value on creation for the created_at field.
	userverification.DefaultCreatedAt = userverificationDescCreatedAt.Default.(func() time.Time)
	// userverificationDescUpdatedAt is the schema descriptor for updated_at field.
	userverificationDescUpdatedAt := userverificationFields[6].Descriptor()
	// userverification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userverification.DefaultUpdatedAt = userverificationDescUpdatedAt.Default.(func() time.Time)
	// userverification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userverification.UpdateDefaultUpdatedAt = userverificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userverificationDescID is the schema descriptor for id field.
	userverificationDescID := userverificationFields[0].Descriptor()
	// userverification.DefaultID holds the default value on creation for the id field.
	userverification.DefaultID = userverificationDescID.Default.(func() uuid.UUID)
}
